// frontend/angular/src/app/live-search/live-search.component.ts
import { Component, OnInit } from '@angular/core';
import { LiveSearchService } from './live-search.service';
import { Highlights, SuggestionHeader, SuggestionBody } from './live-search.model';

@Component({
  selector: 'app-live-search',
  templateUrl: './live-search.component.html',
  styleUrls: ['./live-search.component.scss']
})

export class LiveSearchComponent implements OnInit {

  public value: string = '';

  public showSuggestion: boolean = false;
  public showSuggestionHeader: boolean = false;
  public showSuggestionBody: boolean = false;
  public showWordSuggestion: boolean = false;

  public data: {
    highlights: Array<Highlights>;
    suggestions: Array<string>;
  } | undefined;

  public header: SuggestionHeader = {
    title: '',
    href: '',
    src: ''
  }

  public suggestionArray: Array<SuggestionBody> = [];
  public letters: Array<{
    label: string,
    visible: boolean,
  }> = [];

  private suggestionNav: number = -1;
  private wordSuggestion: string = '';
  private wordOrigin: string = '';

  constructor(
    private liveSearch: LiveSearchService
  ) { }

  ngOnInit(): void {

  }

  private lowercaseWithoutAccent = (text: string) => text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');

  private suggestionHeader(): void {
    this.showSuggestionHeader = false;

    if (this.data?.highlights) {
      this.header.title = '';
      this.header.href = '';
      this.header.src = '';

      this.data.highlights.forEach((highlight: Highlights) => {
        const find = highlight.queries.find((querie: string) =>
          this.lowercaseWithoutAccent(querie) === this.lowercaseWithoutAccent(this.value));

        if (find) {
          this.header.title = highlight.title;
          this.header.src = highlight.logo;
          this.header.href = highlight.url;

          this.showSuggestionHeader = true;
        }

      });
    }
  }

  private suggestionBody(): void {
    this.showSuggestionBody = false;

    if (this.data?.suggestions) {
      this.suggestionArray = [];
      this.data.suggestions.forEach(suggestion => {

        const allWords = suggestion.split(' ');
        const checkWord = allWords.find(wordSearch =>
          this.lowercaseWithoutAccent(wordSearch) === this.lowercaseWithoutAccent(this.value));

        if (checkWord) {
          suggestion = suggestion.replace(checkWord, `<strong>${checkWord}</strong>`);

          this.showSuggestionBody = true;
          this.suggestionArray.push({
            title: suggestion,
            active: false
          });
        } else {
          if (this.value.length >= 3) {
            const getWord = allWords.find(wordSearch =>
              this.lowercaseWithoutAccent(wordSearch.substring(0, this.value.length)) === this.lowercaseWithoutAccent(this.value));

              if (getWord) {
                this.letters = [];
                this.showWordSuggestion = true;

                for (let i = 0; i < getWord.length; i++) {
                    if (this.value.charAt(i) === getWord.charAt(i)) {
                      this.letters.push({
                        label: getWord.charAt(i),
                        visible: false
                      });
                    } else {
                      this.letters.push({
                        label: getWord.charAt(i),
                        visible: true
                      });
                    }
                }

                this.wordOrigin = this.value;
                this.wordSuggestion = getWord;
              }
          }
        }
      });
    }
  }

  public removeHTML(title: string): string {
    return title.replace(/<[^>]*>/g, '');
  }

  public getSuggestions(event: any): void {
    this.value = event.target.value;

    if (
      event.key === 'ArrowDown' ||
      event.key === 'ArrowUp'
    ) {
      this.suggestionArray = this.suggestionArray.map(suggestion => {
        return {
          title: suggestion.title,
          active: false
        }
      });

      if (event.key === 'ArrowDown') {
        if (this.suggestionNav < this.suggestionArray.length - 1) {
          this.suggestionNav++;
        } else {
          this.suggestionNav = 0;
        }
      } else if (event.key === 'ArrowUp') {
        if (this.suggestionNav === 0) {
          this.suggestionNav = (this.suggestionArray.length - 1);
        } else {
          this.suggestionNav--;
        }
      }

      this.suggestionArray[this.suggestionNav].active = true;
      this.value = this.removeHTML(this.suggestionArray[this.suggestionNav].title);

    } else if (event.key === 'ArrowRight') {
      this.showWordSuggestion = false;
      this.value = this.wordSuggestion;

      this.suggestionNav = -1;

      this.suggestionHeader();
      this.suggestionBody();
    } else if (event.key === 'ArrowLeft') {
      this.showWordSuggestion = true;
      this.value = this.wordOrigin;

      this.suggestionHeader();
      this.suggestionBody();
    } else {
      if (this.value.length > 0) {
        this.liveSearch.getData().subscribe((data) => {
          if (data) {
            this.showSuggestion = true;
            this.data = data;

            this.suggestionHeader();
            this.suggestionBody();
          }
        });
      } else {
        this.showSuggestion = false;
        this.showSuggestionHeader = false;
        this.showSuggestionBody = false;
      }
    }
  }
}

<div id="live-search">
  <div class="padding-md margin-botton-md primary">
    <div class="position-relative">
      <span class="ico-mglass"></span>
      <form method="get" class="position-relative" action="http://g1.globo.com/busca/">
        <input
        id="search"
        class="input-field"
        type="search"
        placeholder="Buscar"
        data-type="search"
        autocomplete="off"
        name="q"
        [value]="value"
        (keyup)="getSuggestions($event)"
      />
      <div class="word-suggestion" *ngIf="showWordSuggestion">
        <span *ngFor="let letter of letters" [class.invisible]="!letter.visible">{{ letter.label }}</span>
      </div>
      </form>
      <div class="suggestion" *ngIf="showSuggestion">
            <div class="suggestion-header" *ngIf="showSuggestionHeader">
                <a class="suggestion-header-link" [href]="header.href" [title]="header.title">
                    <img class="suggestion-icon" [src]="header.src" [alt]="header.title">
                    <h2 class="suggestion-title">{{ header.title }}</h2>
                </a>
            </div>
            <div class="suggestion-body" *ngIf="showSuggestionBody">
                <span>Sugestão de busca</span>
                <ul class="suggestion-search">
                  <li *ngFor="let item of this.suggestionArray" [class.active]="item.active">
                    <a href="http://g1.globo.com/busca/?q={{ removeHTML(item.title) }}" [innerHTML]="item.title"></a>
                  </li>
                </ul>
            </div>
            <div class="suggestion-footer">
                <ul>
                    <li>
                        <a class="search-globo" href="http://g1.globo.com/busca/?q={{ value }}" title="buscar na Globo.com">
                          buscar <span class="search-word">'{{ value }}'</span> na Globo.com &#x203A;
                        </a>
                    </li>
                    <li>
                      <a class="search-web" href="https://www.google.com/search?q={{ value }}" title="buscar na Web">
                        buscar <span class="search-word">'{{ value }}'</span> na Web &#x203A;
                      </a>
                    </li>
                </ul>
            </div>
      </div>
    </div>
  </div>
</div>

// frontend/ls-react/src/components/LiveSearch/LiveSearch.js
import React, { useState } from "react";
import axios from "axios";

import {
  Wrapper,
  InputSearch,
  WordSuggestion,
  IcoMglass,
  Suggestion,
  HeaderLink,
  UnorderedList,
  SuggestionIcon,
  SuggestionTitle,
  SuggestionBodyTitle,
  BodyItems,
  BodyItemLink,
  FooterItems,
  LinkFooter,
  SearchWord,
} from "./Style";

const LiveSearch = () => {
  const [searchWord, setSearchWord] = useState('');
  const [value, setValue] = useState('');
  const [isShowSuggestions, setIsShowSuggestions] = useState(false);
  const [isShowSuggestionsHeader, setIsShowSuggestionsHeader] = useState(false);
  const [isShowSuggestionsBody, setIsShowSuggestionsBody] = useState(false);
  const [isShowWordSuggestion, setIsShowWordSuggestion] = useState(false);
  const [data, setData] = useState({});
  const [highlights, setHighlights] = useState({});
  const [suggestionArray, setSuggestionArray] = useState([]);
  const [suggestionNav, setSuggestionNav] = useState(-1);
  const [letters, setLetters] = useState([]);
  const [wordOrigin, setWordOrigin] = useState('');
  const [wordSuggestion, setWordSuggestion] = useState('');

  const lowercaseWithoutAccent = (text) =>
    text
      .toLowerCase()
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "");

  const getJson = () => {
    axios.get(`${process.env.REACT_APP_HOSTNAME}:${process.env.REACT_APP_PORT}`).then((res) => {
      setData(res.data);
    });
  };

  const suggestionHeader = (formattedValue) => {
    if (data.highlights) {
      setHighlights({});

      data.highlights.forEach((highlight) => {
        const find = highlight.queries.find(
          (querie) => lowercaseWithoutAccent(querie) === formattedValue
        );

        if (find) {
          setIsShowSuggestionsHeader(true);
          setHighlights({
            title: highlight.title,
            url: highlight.url,
            logo: highlight.logo,
          });
        }
      });
    }
  };

  const suggestionBody = (formattedValue) => {
    if (data.suggestions) {
      setSuggestionArray([]);
      const suggestionItems = [];

      data.suggestions.forEach((suggestion) => {
        const allWords = suggestion.split(" ");
        const checkWord = allWords.find(
          (wordSearch) =>
            lowercaseWithoutAccent(wordSearch) ===
            lowercaseWithoutAccent(formattedValue)
        );

        if (checkWord) {
          setIsShowSuggestionsBody(true);
          suggestionItems.push({
            title: suggestion.replace(checkWord, `<strong>${checkWord}</strong>`),
            active: false,
          });
        } else {
          if (formattedValue.length >= 3) {
            const getWord = allWords.find(
              (wordSearch) =>
                lowercaseWithoutAccent(wordSearch.substring(0, formattedValue.length)) ===
                lowercaseWithoutAccent(formattedValue)
            );

              if (getWord) {
                let word = [];
                setIsShowWordSuggestion(true);

                for (let i = 0; i < getWord.length; i++) {
                    if (formattedValue.charAt(i) === getWord.charAt(i)) {
                      word.push({
                        label: getWord.charAt(i),
                        visible: false
                      });
                    } else {
                      word.push({
                        label: getWord.charAt(i),
                        visible: true
                      });
                    }
                }

                setLetters(word);
                setWordOrigin(formattedValue);
                setWordSuggestion(getWord);
              }
          }
        }
      });

      setSuggestionArray(suggestionItems);
    }
  };

  const getSuggestions = (event) => {
    const value = event.target.value;
    setSearchWord(value);

    if (value.length === 0) {
      setIsShowSuggestions(false);
      setIsShowSuggestionsBody(false);
      setIsShowWordSuggestion(false);

      return;
    }

    if (
      event.key === "ArrowDown" || 
      event.key === "ArrowUp"
    ) {
      setSuggestionArray(
        suggestionArray.map((suggestion) => {
          return {
            title: suggestion.title,
            active: false,
          };
        })
      );

      let nav = suggestionNav;

      if (event.key === "ArrowDown") {
        if (nav < suggestionArray.length - 1) {
          nav++;
        } else {
          nav = 0;
        }
      } else if (event.key === "ArrowUp") {
        if (nav === 0) {
          nav = suggestionArray.length - 1;
        } else {
          nav--;
        }
      }

      const newSuggestionArray = suggestionArray.map((suggestion, index) => {
        return {
            title: suggestion.title,
            active: index === nav,
          };
      });

      setSuggestionArray(newSuggestionArray);
      setValue(removeHTML(suggestionArray[nav].title));
      setSearchWord(removeHTML(suggestionArray[nav].title));

      setSuggestionNav(nav);
    } else if (event.key === "ArrowRight") {
      setIsShowWordSuggestion(false);
      setValue(wordSuggestion);

      suggestionHeader(wordSuggestion);
      suggestionBody(wordSuggestion);
      setSearchWord(wordSuggestion);

      setSuggestionNav(-1);
    } else if (event.key === "ArrowLeft") {
      setIsShowWordSuggestion(true);
      setValue(wordOrigin);

      suggestionHeader(wordOrigin);
      suggestionBody(wordOrigin);
      setSearchWord(wordOrigin);
    } else {
      setIsShowSuggestions(true);
      getJson();

      const formattedValue = lowercaseWithoutAccent(value);
      suggestionHeader(formattedValue);
      suggestionBody(formattedValue);
    }
  };

  const getValue = (value) => {
    setValue(value);
  }
  
  const createMarkup = (html) => {
    return { __html: html };
  }  

  const removeHTML = (html) => {
    return html.replace(/<[^>]*>/g, '')    ;
  }

  return (
    <div id="live-search">
      <Wrapper>
        <div>
          <IcoMglass />
          <form method="get" action="http://g1.globo.com/busca/">
            <InputSearch
              id="search"
              className="input-field"
              type="search"
              placeholder="Buscar"
              data-type="search"
              autoComplete="off"
              name="q"
              value={value}
              onKeyUp={(e) => getSuggestions(e)}
              onChange={(e) => getValue(e.target.value)}
            />
            {isShowWordSuggestion && (
              <WordSuggestion>
                {letters.map((item, index) => {
                  return (
                    <span className={!item.visible ? 'invisible' : null} key={index}>{ item.label }</span>
                  );
                })}
            </WordSuggestion>
            )}
          </form>
          {isShowSuggestions && (
            <Suggestion>
              {isShowSuggestionsHeader && highlights && (
                <div className="suggestion-header">
                  <HeaderLink href={highlights.url} title={highlights.title}>
                    <SuggestionIcon
                      src={highlights.logo}
                      alt={highlights.title}
                      title={highlights.title}
                    />
                    <SuggestionTitle>{highlights.title}</SuggestionTitle>
                  </HeaderLink>
                </div>
              )}
              {isShowSuggestionsBody && suggestionArray.length > 0 && (
                <div className="suggestion-body">
                  <SuggestionBodyTitle>Sugestão de busca</SuggestionBodyTitle>
                  <UnorderedList className="suggestion-search">
                    {suggestionArray.map((item, index) => {
                      return (
                        <BodyItems
                          key={index}
                          className={`${item.active ? "active" : ""}`}
                        >
                          <BodyItemLink href={`http://g1.globo.com/busca/?q=${removeHTML(item.title)}`} dangerouslySetInnerHTML={createMarkup(item.title)}>
                          </BodyItemLink>
                        </BodyItems>
                      );
                    })}
                  </UnorderedList>
                </div>
              )}
              <div className="suggestion-footer">
                <UnorderedList>
                  <FooterItems>
                    <LinkFooter
                      href={`http://g1.globo.com/busca/?q=${searchWord}`}
                      title="buscar na Globo.com"
                    >
                      buscar <SearchWord>{searchWord}</SearchWord> na Globo.com
                      &#x203A;
                    </LinkFooter>
                  </FooterItems>
                  <FooterItems>
                    <LinkFooter
                      href={`https://www.google.com/search?q=${searchWord}`}
                      title="buscar na Web"
                    >
                      buscar <SearchWord>{searchWord}</SearchWord> na Web
                      &#x203A;
                    </LinkFooter>
                  </FooterItems>
                </UnorderedList>
              </div>
            </Suggestion>
          )}
        </div>
      </Wrapper>
    </div>
  );
};

export default LiveSearch;
